services:
  nestjs-boilerplate-postgres:
    image: postgres:latest
    container_name: nestjs-boilerplate-postgres
    hostname: nestjs-boilerplate-postgres
    env_file:
      - .env.prod
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - nestjs-boilerplate-postgres-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - nestjs-boilerplate-network

  nestjs-boilerplate-redis:
    image: redis:latest
    container_name: nestjs-boilerplate-redis
    hostname: nestjs-boilerplate-redis
    env_file:
      - .env.prod
    command: ['redis-server', '--requirepass ${REDIS_PASSWORD}']
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - nestjs-boilerplate-redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', '--no-auth-warning', '-a', '${REDIS_PASSWORD}', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'
    networks:
      - nestjs-boilerplate-network

  nestjs-boilerplate-redis-insight:
    image: redislabs/redisinsight:latest
    container_name: nestjs-boilerplate-redis-insight
    hostname: nestjs-boilerplate-redis-insight
    user: '0:0'
    env_file:
      - .env.prod
    ports:
      - '5540:5540'
    networks:
      - nestjs-boilerplate-network
    restart: always
    volumes:
      - nestjs-boilerplate-redis-insight-data:/usr/src/app/redisinsight/api/data
    environment:
      - REDISINSIGHT_DISABLE_ENCRYPTION=1
    command: >
      sh -c "
      mkdir -p /usr/src/app/redisinsight/api/data &&
      chown -R node:node /usr/src/app/redisinsight/api/data &&
      ./docker-entry.sh
      "
    depends_on:
      nestjs-boilerplate-redis:
        condition: service_healthy

  nestjs-boilerplate-prometheus:
    image: prom/prometheus:latest
    container_name: nestjs-boilerplate-prometheus
    hostname: nestjs-boilerplate-prometheus
    ports:
      - '${PROMETHEUS_PORT}:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--storage.tsdb.retention.time=30d'
    restart: unless-stopped
    networks:
      - nestjs-boilerplate-network
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:9090/-/healthy']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  nestjs-boilerplate-grafana:
    image: grafana/grafana:latest
    container_name: nestjs-boilerplate-grafana
    hostname: nestjs-boilerplate-grafana
    ports:
      - '${GRAFANA_PORT}:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/
      - GF_SERVER_DOMAIN=${GRAFANA_DOMAIN}
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
    depends_on:
      nestjs-boilerplate-prometheus:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - nestjs-boilerplate-grafana-data:/var/lib/grafana
    networks:
      - nestjs-boilerplate-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  nestjs-boilerplate-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: nestjs-boilerplate-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'
    networks:
      - nestjs-boilerplate-network

  nestjs-boilerplate-kafka-broker:
    image: confluentinc/cp-kafka:latest
    hostname: nestjs-boilerplate-kafka-broker
    ports:
      - '19092:19092'
    depends_on:
      - nestjs-boilerplate-zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'nestjs-boilerplate-zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://nestjs-boilerplate-kafka-broker:9092,PLAINTEXT_INTERNAL://localhost:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - nestjs-boilerplate-network

  nestjs-boilerplate-kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: nestjs-boilerplate-kafka-ui
    depends_on:
      - nestjs-boilerplate-kafka-broker
    ports:
      - '8080:8080'
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: nestjs-boilerplate-kafka-broker:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: nestjs-boilerplate-zookeeper:2181
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: SCRAM-SHA-512
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USER}" password="${KAFKA_PASSWORD}";
    networks:
      - nestjs-boilerplate-network

  nestjs-boilerplate-app:
    container_name: nestjs-boilerplate-app
    restart: on-failure
    env_file:
      - .env.prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - nestjs-boilerplate-postgres
      - nestjs-boilerplate-redis
      - nestjs-boilerplate-redis-insight
      - nestjs-boilerplate-prometheus
      - nestjs-boilerplate-grafana
      - nestjs-boilerplate-zookeeper
      - nestjs-boilerplate-kafka-broker
      - nestjs-boilerplate-kafka-ui
    networks:
      - nestjs-boilerplate-network

networks:
  nestjs-boilerplate-network:
    name: nestjs-boilerplate-network
    driver: bridge
    attachable: true

volumes:
  nestjs-boilerplate-postgres-data:
    driver: local
  nestjs-boilerplate-redis-data:
  nestjs-boilerplate-grafana-data:
  nestjs-boilerplate-zookeeper-data:
  nestjs-boilerplate-kafka-data:
  nestjs-boilerplate-redis-insight-data:
